'use server';
import { createClient } from '@/lib/supabase/server'; import { redirect } from 'next/navigation'; import { revalidatePath } from 'next/cache';

function slugify(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');}
function safeFile(name:string){return name.toLowerCase().replace(/[^a-z0-9.]+/g,'-');}
async function assertAdmin(){const s=await createClient(); const {data}=await s.auth.getClaims(); const uid=data?.claims?.sub; if(!uid) redirect('/admin/login'); const {data:a}=await s.from('admin_users').select('user_id').eq('user_id',uid).maybeSingle(); if(!a) redirect('/admin/login'); return s;}
async function upload(s:any,bucket:string,file:File,prefix:string){ if(!file||file.size===0)return null; const max=bucket==='product-images'?10*1024*1024:20*1024*1024; if(file.size>max) throw new Error('File too large'); const path=`${prefix}/${crypto.randomUUID()}-${safeFile(file.name)}`; const {error}=await s.storage.from(bucket).upload(path,file,{cacheControl:'3600',upsert:false}); if(error) throw error; const {data}=s.storage.from(bucket).getPublicUrl(path); return {path,url:data.publicUrl}; }

export async function createProduct(formData:FormData){ const s=await assertAdmin(); const name=String(formData.get('name')||'').trim(); if(!name) redirect('/admin/products/new?error=name');
  let main=null, spec=null; try { main=await upload(s,'product-images',formData.get('main_image') as File,'main'); spec=await upload(s,'product-files',formData.get('specification') as File,'specifications'); } catch { redirect('/admin/products/new?error=upload'); }
  const payload={name,slug:slugify(String(formData.get('slug')||name)),category:String(formData.get('category')||'Herbs'),short_description:String(formData.get('short_description')||'')||null,description:String(formData.get('description')||'')||null,origin:String(formData.get('origin')||'Egypt'),form:String(formData.get('form')||'Dried'),packaging:String(formData.get('packaging')||'')||null,minimum_order:String(formData.get('minimum_order')||'')||null,availability:String(formData.get('availability')||'Available on request'),quality_label:String(formData.get('quality_label')||'Premium Quality'),main_image_url:main?.url||null,main_image_path:main?.path||null,specification_url:spec?.url||null,specification_path:spec?.path||null,featured:formData.get('featured')==='on',is_visible:formData.get('is_visible')==='on',sort_order:Number(formData.get('sort_order')||0)};
  const {data,error}=await s.from('products').insert(payload).select('id').single(); if(error) redirect('/admin/products/new?error=save');
  const gallery=formData.getAll('gallery_images').filter((v):v is File=>v instanceof File&&v.size>0); for(let i=0;i<gallery.length;i++){try{const im=await upload(s,'product-images',gallery[i],'gallery'); if(im) await s.from('product_images').insert({product_id:data.id,image_url:im.url,image_path:im.path,sort_order:i});}catch{}}
  revalidatePath('/'); revalidatePath('/products'); redirect('/admin/products?saved=1'); }

export async function updateProduct(formData:FormData){ const s=await assertAdmin(); const id=String(formData.get('id')||''); if(!id) redirect('/admin/products'); const name=String(formData.get('name')||'').trim();
  const {data:existing}=await s.from('products').select('*').eq('id',id).single(); if(!existing) redirect('/admin/products'); let main=null,spec=null; try{main=await upload(s,'product-images',formData.get('main_image') as File,'main'); spec=await upload(s,'product-files',formData.get('specification') as File,'specifications');}catch{redirect(`/admin/products/${id}?error=upload`)}
  if(main&&existing.main_image_path) await s.storage.from('product-images').remove([existing.main_image_path]); if(spec&&existing.specification_path) await s.storage.from('product-files').remove([existing.specification_path]);
  const payload={name,slug:slugify(String(formData.get('slug')||name)),category:String(formData.get('category')||'Herbs'),short_description:String(formData.get('short_description')||'')||null,description:String(formData.get('description')||'')||null,origin:String(formData.get('origin')||'Egypt'),form:String(formData.get('form')||'Dried'),packaging:String(formData.get('packaging')||'')||null,minimum_order:String(formData.get('minimum_order')||'')||null,availability:String(formData.get('availability')||'Available on request'),quality_label:String(formData.get('quality_label')||'Premium Quality'),main_image_url:main?.url||existing.main_image_url,main_image_path:main?.path||existing.main_image_path,specification_url:spec?.url||existing.specification_url,specification_path:spec?.path||existing.specification_path,featured:formData.get('featured')==='on',is_visible:formData.get('is_visible')==='on',sort_order:Number(formData.get('sort_order')||0),updated_at:new Date().toISOString()};
  const {error}=await s.from('products').update(payload).eq('id',id); if(error) redirect(`/admin/products/${id}?error=save`);
  const gallery=formData.getAll('gallery_images').filter((v):v is File=>v instanceof File&&v.size>0); const {count}=await s.from('product_images').select('*',{head:true,count:'exact'}).eq('product_id',id); for(let i=0;i<gallery.length;i++){try{const im=await upload(s,'product-images',gallery[i],'gallery'); if(im) await s.from('product_images').insert({product_id:id,image_url:im.url,image_path:im.path,sort_order:(count??0)+i});}catch{}}
  revalidatePath('/'); revalidatePath('/products'); revalidatePath(`/products/${payload.slug}`); redirect(`/admin/products/${id}?saved=1`); }

export async function deleteProduct(formData:FormData){ const s=await assertAdmin(); const id=String(formData.get('id')||''); const {data:p}=await s.from('products').select('main_image_path,specification_path').eq('id',id).single(); const {data:gallery}=await s.from('product_images').select('image_path').eq('product_id',id); if(p?.main_image_path) await s.storage.from('product-images').remove([p.main_image_path]); if(p?.specification_path) await s.storage.from('product-files').remove([p.specification_path]); if(gallery?.length) await s.storage.from('product-images').remove(gallery.map(x=>x.image_path)); await s.from('products').delete().eq('id',id); revalidatePath('/'); revalidatePath('/products'); redirect('/admin/products?deleted=1'); }

export async function deleteGalleryImage(formData:FormData){const s=await assertAdmin(); const id=String(formData.get('image_id')||''); const productId=String(formData.get('product_id')||''); const {data}=await s.from('product_images').select('image_path').eq('id',id).single(); if(data?.image_path) await s.storage.from('product-images').remove([data.image_path]); await s.from('product_images').delete().eq('id',id); revalidatePath(`/admin/products/${productId}`);}
